# Generated by Django 4.1.2 on 2023-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BypassDM_V1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="key",
            field=models.TextField(null=True),
        ),
    ]
