# Generated by Django 4.1.7 on 2023-03-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0001_initial'),
        ('BypassDM_V1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.twitteruser')),
            ],
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
