# Generated by Django 4.1.2 on 2023-03-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BypassDM_V1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="twitter_user_ids",
        ),
        migrations.AddField(
            model_name="tweet",
            name="id_twitter_user",
            field=models.CharField(default="", max_length=100),
        ),
    ]
