# Generated by Django 4.1.2 on 2023-03-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BypassDM_V1", "0002_remove_tweet_twitter_user_ids_tweet_id_twitter_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="id_twitter_user",
            new_name="twitter_userid",
        ),
    ]
