# Generated by Django 4.1.7 on 2023-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0002_tweet_delete_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twitter_users_id',
            field=models.IntegerField(default=0),
        ),
    ]
