# Generated by Django 4.1.7 on 2023-03-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0003_tweet_twitter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='twitter_users_id',
        ),
    ]
