# Generated by Django 4.1.7 on 2023-03-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0005_tweet_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='twitter_user',
            new_name='twitter_user_id',
        ),
    ]
