# Generated by Django 4.1.7 on 2023-03-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0006_rename_twitter_user_tweet_twitter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='twitter_user_id',
            new_name='twitter_user',
        ),
    ]
