# Generated by Django 4.1.7 on 2023-03-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0007_rename_twitter_user_id_tweet_twitter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twitter_user_ids',
            field=models.CharField(default='', max_length=100),
        ),
    ]
