# Generated by Django 4.1.7 on 2023-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0008_tweet_twitter_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='encrypted_message',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='key',
            field=models.BinaryField(null=True),
        ),
    ]
