# Generated by Django 4.1.7 on 2023-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BypassDM_V1', '0009_encryptedmessage_tweet_encrypted_message_tweet_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='encrypted_message',
        ),
        migrations.AddField(
            model_name='encryptedmessage',
            name='encrypted_message',
            field=models.BinaryField(null=True),
        ),
    ]
